### PR TITLE
Fix i18n.yml

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
Fix i18n.yml pb !! #56

### CODE REVIEW

**Comment by celyes** [comment]
Why would you delete the content of this file ?

**Comment by 3imed-jaberi** [comment]
<div dir='rtl'>
@celyes, يجب اصلاح هذا لذالك قمت بإعادة الفتح ...

**Comment by 3imed-jaberi** [comment]
> Why would you delete the content of this file ?

<div dir='rtl'>
@celyes, يجب اصلاح هذا لذالك قمت بإعادة الفتح ...

**Comment by 3imed-jaberi** [comment]
> Why would you delete the content of this file ?

<div dir='rtl'>
@celyes, يجب اصلاح هذا ...

**Comment by 3imed-jaberi** [comment]
I'll close this now ,nchlh when we communicate we will talk more ..

**Pull request closed without merging**
